# Generated by Django 4.1.4 on 2024-01-04 10:28

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("title", models.CharField(blank=True, max_length=250, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("videoURL", models.URLField(blank=True, null=True)),
                ("photo", models.ImageField(upload_to="newsImage", verbose_name="Image of News")),
                ("viewCount", models.IntegerField(default=0)),
                ("status", models.BooleanField(default=False)),
                ("isActual", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
