# Generated by Django 4.2.5 on 2024-03-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="middle_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
