# Generated by Django 4.2.5 on 2023-12-22 20:36

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "photo_uz",
                    models.ImageField(blank=True, null=True, upload_to="bannerImage", verbose_name="Image of Banner"),
                ),
                (
                    "photo_ru",
                    models.ImageField(blank=True, null=True, upload_to="bannerImage", verbose_name="Image of Banner"),
                ),
                ("url", models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
