# Generated by Django 4.1.4 on 2024-01-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_file_remove_product_discountprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="code",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.IntegerField(choices=[(1, "DRAFT"), (2, "ACTIVE"), (3, "DELETED")], default=2),
        ),
    ]
