# Generated by Django 4.2.5 on 2024-02-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=50),
        ),
    ]
