# Generated by Django 4.2.5 on 2023-12-22 21:02

import common.users.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", common.users.managers.UserManager()),
            ],
        ),
    ]
