# Generated by Django 4.2.5 on 2023-12-22 20:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("code", models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
                ("totalAmount", models.FloatField(default=0)),
                ("orderedTime", models.DateTimeField(default=django.utils.timezone.now)),
                ("deliveredTime", models.DateTimeField(blank=True, null=True)),
                ("installation", models.BooleanField(default=False)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "paymentStatus",
                    models.CharField(
                        choices=[
                            ("waiting", "WAITING"),
                            ("preauth", "PREAUTH"),
                            ("confirmed", "CONFIRMED"),
                            ("rejected", "REJECTED"),
                            ("refunded", "REFUNDED"),
                            ("error", "ERROR"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                (
                    "paymentType",
                    models.IntegerField(choices=[(1, "PAYME"), (2, "CLICK"), (3, "UZUM"), (4, "CASH")], default=4),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "PAYMENT"),
                            (1, "PENDING"),
                            (2, "WAITING"),
                            (3, "DELIVERED"),
                            (4, "CANCELED"),
                            (5, "IN_PROGRESS"),
                            (6, "DELETED"),
                        ],
                        default=0,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="OrderProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("quantity", models.FloatField()),
                ("orderPrice", models.FloatField()),
                ("discount", models.FloatField(default=0)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="product.product")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
