# Generated by Django 4.1.4 on 2024-01-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="orderPrice",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
