# Generated by Django 4.2.5 on 2024-02-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_alter_orderproduct_orderprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="orderPrice",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=50),
        ),
    ]
